name: Keep Render Service Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Service
        run: |
          echo "Pinging Render service..."
          curl -f https://bellavista-backend-3.onrender.com/api/tours/stats/ || echo "Ping failed"
          echo "Ping completed at $(date)"